/*
* uniao do funcionario com mais vendas com o funcionario com mais horas de reparacao
*/


.mode columns
.headers on
.nullvalue NULL 


--Funcionario com o maior numero de Vendas
SELECT NOME,MAX(COUNT_TABLE.COUNT_VENDA) AS NR_VENDAS
FROM FUNCIONARIO JOIN
        (SELECT ID_FUNCIONARIO, COUNT(*) AS COUNT_VENDA
        FROM INCREMENTO_VENDA
        GROUP BY ID_FUNCIONARIO) AS COUNT_TABLE
ON COUNT_TABLE.ID_FUNCIONARIO = FUNCIONARIO.ID_FUNCIONARIO
UNION
--Funcionario com o maior numero de reparações
SELECT NOME,MAX(COUNT_TABLE.COUNT_REPARACAO) AS NR_REPARACOES
FROM FUNCIONARIO JOIN
        (SELECT ID_FUNCIONARIO, COUNT(*) AS COUNT_REPARACAO
        FROM INCREMENTO_REPARACAO
        GROUP BY ID_FUNCIONARIO) AS COUNT_TABLE
ON COUNT_TABLE.ID_FUNCIONARIO = FUNCIONARIO.ID_FUNCIONARIO;
