/* Interrogacao :
Marca favorita pelos clientes nas reparacoes
*/
.mode columns
.headers on
.nullvalue NULL 

DROP VIEW IF EXISTS MAXIMO;

CREATE VIEW MAXIMO AS
SELECT ID_PECA, PECA_FAVORITA,MAX(PECA_FAVORITA) AS QUANTIDADE
FROM(SELECT ID_PECA,COUNT(ID_PECA) AS PECA_FAVORITA 
FROM REPARACAO 
NATURAL JOIN PECA_REPARACAO GROUP BY ID_PECA) GROUP BY ID_PECA; -- a QUANTIDADE MAXIMA DE PECAS USADAS CHECK

DROP VIEW IF EXISTS FAVORITES;
CREATE VIEW FAVORITES AS
SELECT a.ID_PECA,a.QUANTIDADE FROM MAXIMO a 
INNER JOIN (SELECT MAX(PECA_FAVORITA) 
AS T FROM MAXIMO)b ON a.QUANTIDADE = b.T;


SELECT NOME as "Marcas Favoritas"
FROM PECA NATURAL JOIN FORNECEDOR NATURAL JOIN PECA_FORNECEDOR NATURAL JOIN FAVORITES; --NOME CORRESPONENTE AO ID DA PECA CHECK
